### Случайная непрерывная величина A имеет равномерное распределение на промежутке (200, 800]. Найдите ее среднее значение и дисперсию.

In [4]:
M = (200+800)/2
print (f'Среднее значение равно {M}')

Среднее значение равно 500.0


In [5]:
sig2 = (800-200)**2/12
print (f'Дисперсия равна {sig2}')

Дисперсия равна 30000.0


### О случайной непрерывной равномерно распределенной величине B известно, что ее дисперсия равна 0.2. Можно ли найти правую границу величины B и ее среднее значение зная, что левая граница равна 0.5? Если да, найдите ее.

s2 = (a-0.5)**2/12



(a-0.5)**2 = 2.4

In [20]:
import math
b = math.sqrt(2.4)
a = 0.5-b
c = 0.5+b
a,c


(-1.0491933384829668, 2.049193338482967)

In [21]:
print (f'Правая граница равна {c}, так как больше 0.5')

Правая граница равна 2.049193338482967, так как больше 0.5


In [23]:
M = (c+0.5)/2
print (f'Среднее равно {M}')

Среднее равно 1.2745966692414834


### Непрерывная случайная величина X распределена нормально и задана плотностью распределения 
f(x) = (1 / (4 * sqrt(2pi))) * exp((-(x+2)**2) / 32)

Согласно формуле плотности распределения для нормального распределения, найдем нужные показатели из данной функции

In [25]:
print (f'M(x) = -2')
print(f'2sigma**2 = 32')


M(x) = -2
2sigma**2 = 32


D(x) = 16

std(x)=+-4

### Рост взрослого населения города X имеет нормальное распределение. Причем, средний рост равен 174 см, а среднее квадратичное отклонение равно 8 см.
Какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:

Воспользуемся формулой Z= (X-μ)/σ и z таблицами

а). больше 182 см

In [26]:
z = (182-174)/8
z

1.0

In [32]:
print(f'Вероятность того, что рост выбранного человека будет больше 182 см равна {round((1-0.84134)*100,2)} %')

Вероятность того, что рост выбранного человека будет больше 182 см равна 15.87 %


б). больше 190 см

In [33]:
print(f'Вероятность того, что рост выбранного человека будет больше 190 см равна {round((1-0.97725)*100,2)} %')

Вероятность того, что рост выбранного человека будет больше 190 см равна 2.28 %


в). от 166 см до 190 см

In [37]:
print(f'Вероятность того, что рост выбранного человека будет 166-190 см равна {round((1-(1-0.97725)-0.15866)*100,2)} %')

Вероятность того, что рост выбранного человека будет 166-190 см равна 81.86 %


г). от 166 см до 182 см

In [38]:
print(f'Вероятность того, что рост выбранного человека будет 166-182 см равна {round((1-(1-0.84134)-0.15866)*100,2)} %')

Вероятность того, что рост выбранного человека будет 166-182 см равна 68.27 %


д). от 158 см до 190 см

In [39]:
print(f'Вероятность того, что рост выбранного человека будет 158-190 см равна {round((1-(1-0.97725)-0.02275)*100,2)} %')

Вероятность того, что рост выбранного человека будет 158-190 см равна 95.45 %


е). не выше 150 см или не ниже 190 см

In [41]:
print(f'Вероятность того, что рост выбранного человека будет не выше 150 см или не ниже 190 см равна {round((0.00135+(1-0.97725))*100,2)} %')

Вероятность того, что рост выбранного человека будет не выше 150 см или не ниже 190 см равна 2.41 %


ё). не выше 150 см или не ниже 198 см

In [46]:
print(f'Вероятность того, что рост выбранного человека будет не выше 150 или не ниже 198 см равна {round((0.00135+1-0.99865)*100,2)} %')

Вероятность того, что рост выбранного человека будет не выше 150 или не ниже 198 см равна 0.27 %


ж). ниже 166 см.

In [48]:
print(f'Вероятность того, что рост выбранного человека будет ниже 166 см равна {round(0.15866*100,2)} %')

Вероятность того, что рост выбранного человека будет ниже 166 см равна 15.87 %


### 5. На сколько сигм (средних квадратичных отклонений) отклоняется рост человека, равный 190 см, от математического ожидания роста в популяции, в которой M(X) = 178 см и D(X) = 25 кв.см?

In [50]:
print (f'На {(190-178)/5} сигм')

На 2.4 сигм
